brouzie_crossdomain_auth_server_check_auth:
    path: /check-crossdomain-auth
    host: %brouzie.crossdomain_auth.authentication_server.host%
    schemes:  [%brouzie.crossdomain_auth.authentication_server.scheme%]
    defaults: {_controller: BrouzieCrossdomainAuthBundle:Server:checkAuthentication }

