brouzie_crossdomain_auth_login_check:
    path: /crossdomain_authentication

#TODO: load dynamically or add here support of the https
brouzie_crossdomain_auth_server_check_auth:
    path: /check-auth
    host: %brouzie.crossdomain_auth.authentication_server.host%
    defaults: {_controller: BrouzieCrossdomainAuthBundle:Server:checkAuthentication }

